- name: Deploy Docker container on EC2
  hosts: web
  become: true
  tasks:
    - name: Update apt and install Docker (for Ubuntu-based AMI)
      apt:
        update_cache: yes
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker (for Amazon Linux 2)
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull latest Docker image
      docker_image:
        name: ghcr.io/DimitarDTsonev/DevOps_Project
        tag: "latest"

    - name: Run the container
      docker_container:
        name: flask-app
        image: ghcr.io/DimitarDTsonev/DevOps_Project:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"